version: 2.1
jobs:
  build:
    docker:
      - image: dimtass/stm32-cde-image:0.1
    steps:
      - checkout
      - run:
          name: Build firmware
          command: |
            git submodule sync
            git submodule update --init --recursive
            CLEANBUILD=true USE_DBGUART=ON USE_STDPERIPH_DRIVER=ON SRC=src_stdperiph ./build.sh && CLEANBUILD=true USE_DBGUART=ON USE_STDPERIPH_DRIVER=ON USE_FREERTOS=ON SRC=src_freertos ./build.sh